Create README.md for examples/solana_native/basic_nft
Codigo-io/issues pull request #88
Opened 2023-10-16 20:09 UTC by AbhimanyuAjudiya

2023-10-24 23:45 UTC, JazielGuerrero requested changes

2023-10-24 23:45 UTC, JazielGuerrero commented on examples/solana_native/basic_nft/README.md
> +In this Quickstart guide, you’ll learn how to start with Código’s Interface Description Language (CIDL) by building a simple Solana counter program.
Please change "counter program" to "basic NFT program"

2023-10-24 23:45 UTC, JazielGuerrero commented on examples/solana_native/basic_nft/README.md
> +In the `program` directory, you will find a directory called `src`; inside this directory, there will be two `.rs` files named `mint.rs`, `burn.rs` and `transfer.rs`
Please change "there will be two" to "there will be three"

2023-10-24 23:45 UTC, JazielGuerrero commented on examples/solana_native/basic_nft/README.md
> +Open the terminal and navigate to the `program` directory, from there execute the following command:
Please change "Open the terminal and navigate to the `program` directory" to "Open the terminal and navigate to the `program` directory by executing the command `cd program`"

2023-10-24 23:45 UTC, JazielGuerrero commented on examples/solana_native/basic_nft/README.md
> +If it gives an error then run the following command:
Based on the above comment, we can remove this text (including the suggested command)

2023-10-24 23:45 UTC, JazielGuerrero commented on examples/solana_native/basic_nft/README.md
> +solana program deploy target/deploy/counter.so
Please change "counter.so" to "nft".so since that will be the name of the file

2023-10-24 23:45 UTC, JazielGuerrero commented on examples/solana_native/basic_nft/README.md
> +    const connection = new Connection("https://api.devnet.solana.com", {
Change "https://api.devnet.solana.com" for "http://127.0.0.1:8899" since based on the above commands it will be deployed to this validator

2023-10-24 23:45 UTC, JazielGuerrero commented on examples/solana_native/basic_nft/README.md
> +    const args = process.argv.slice(2);
Remove this line

2023-10-24 23:45 UTC, JazielGuerrero commented on examples/solana_native/basic_nft/README.md
> +    const progId = new PublicKey(args[0]!);
Replace it for `const progId = new PublicKey("PASTE_YOUR_PROGRAM_ID");` since based on the doc this code will be expected to be there

2023-10-24 23:45 UTC, JazielGuerrero commented on examples/solana_native/basic_nft/README.md
> +npm install ts-node --save-dev
Please change the command for `npm install ts-node @solana/spl-token --save-dev`

2023-10-25 00:31 UTC, AbhimanyuAjudiya reviewed
I have changed the file as per you said, thanks for helping me.

2023-10-25 00:31 UTC, JazielGuerrero approved these changes

2023-10-25 00:32 UTC, merged

2023-10-25 00:33 UTC, JazielGuerrero commented
Thanks for your contribution